// ============================================================
// CMOMS - Seed Data (Realistic Demo Data)
// ============================================================

import { AuditLog, Client, ContentType, CreativeTask, Holiday, MotionTask, Notification, Role, TaskRevision, User } from './types';
import { generateUUID } from './utils';

// --- ROLES ---
export const SEED_ROLES: Role[] = [
  { id: 1, name: 'ADMIN', label: 'Admin', description: 'System Administrator - Full access to all modules & master data', created_at: '2026-01-01T00:00:00Z' },
  { id: 2, name: 'TEAM_LEAD', label: 'Team Lead', description: 'Creative Director / Team Lead - Triage, assign, approve & team capacity', created_at: '2026-01-01T00:00:00Z' },
  { id: 3, name: 'STRATEGIC_PIC', label: 'Strategic (Creative Strategic)', description: 'Creative Strategic - Visual concept, illustration ideas & brand checklist', created_at: '2026-01-01T00:00:00Z' },
  { id: 4, name: 'DESIGNER', label: 'GD (Graphic Designer)', description: 'Graphic Designer - Design production, concept review & asset handover', created_at: '2026-01-01T00:00:00Z' },
  { id: 5, name: 'MOTION_PIC', label: 'Motion (Motion Designer)', description: 'Motion Designer - Animation production, preview links & OP handover', created_at: '2026-01-01T00:00:00Z' },
  { id: 6, name: 'REQUESTER', label: 'AE (Account Executive)', description: 'Account Executive - Brief creation, client liaison & approval follow-up', created_at: '2026-01-01T00:00:00Z' },
  { id: 7, name: 'OPERATOR', label: 'OP (Operator)', description: 'Live Stream Operator - Last checkpoint & live broadcast execution', created_at: '2026-01-01T00:00:00Z' },
];

// --- USERS ---
const USER_IDS = {
  admin: 'u-admin-001',
  alfie: 'u-lead-alfie',
  ira: 'u-strat-ira',
  mahes: 'u-strat-mahes',
  nadya: 'u-des-nadya',
  yusuf: 'u-des-yusuf',
  bad: 'u-des-bad',
  jova: 'u-mot-jova',
  bima: 'u-mot-bima',
  sarah: 'u-req-sarah',
  reza: 'u-req-reza',
  sam: 'u-op-sam',
};

export const SEED_USERS: User[] = [
  { id: USER_IDS.admin, email: 'admin@orbiz.id', password_hash: 'admin123', full_name: 'System Admin', avatar_initials: 'SA', role_id: 1, role_name: 'ADMIN', daily_capacity_points: 0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.alfie, email: 'alfie@orbiz.id', password_hash: 'alfie123', full_name: 'Alfie Rahman', avatar_initials: 'AR', role_id: 2, role_name: 'TEAM_LEAD', daily_capacity_points: 7.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.ira, email: 'ira@orbiz.id', password_hash: 'ira123', full_name: 'Ira Kusuma', avatar_initials: 'IK', role_id: 3, role_name: 'STRATEGIC_PIC', daily_capacity_points: 5.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.mahes, email: 'mahes@orbiz.id', password_hash: 'mahes123', full_name: 'Mahes Wardana', avatar_initials: 'MW', role_id: 3, role_name: 'STRATEGIC_PIC', daily_capacity_points: 5.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.nadya, email: 'nadya@orbiz.id', password_hash: 'nadya123', full_name: 'Nadya Aulia', avatar_initials: 'NA', role_id: 4, role_name: 'DESIGNER', daily_capacity_points: 5.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.yusuf, email: 'yusuf@orbiz.id', password_hash: 'yusuf123', full_name: 'Yusuf Pratama', avatar_initials: 'YP', role_id: 4, role_name: 'DESIGNER', daily_capacity_points: 7.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.bad, email: 'bad@orbiz.id', password_hash: 'bad123', full_name: 'Badriyah Sari', avatar_initials: 'BS', role_id: 4, role_name: 'DESIGNER', daily_capacity_points: 7.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.jova, email: 'jova@orbiz.id', password_hash: 'jova123', full_name: 'Jova Dirgantara', avatar_initials: 'JD', role_id: 5, role_name: 'MOTION_PIC', daily_capacity_points: 7.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.bima, email: 'bima@orbiz.id', password_hash: 'bima123', full_name: 'Bima Saputra', avatar_initials: 'BS', role_id: 5, role_name: 'MOTION_PIC', daily_capacity_points: 7.0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.sarah, email: 'sarah@orbiz.id', password_hash: 'sarah123', full_name: 'Sarah Amelia', avatar_initials: 'SA', role_id: 6, role_name: 'REQUESTER', daily_capacity_points: 0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.reza, email: 'reza@orbiz.id', password_hash: 'reza123', full_name: 'Reza Firmansyah', avatar_initials: 'RF', role_id: 6, role_name: 'REQUESTER', daily_capacity_points: 0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: USER_IDS.sam, email: 'sam@orbiz.id', password_hash: 'sam123', full_name: 'Sam Operator', avatar_initials: 'SO', role_id: 7, role_name: 'OPERATOR', daily_capacity_points: 0, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
];

// --- CLIENTS / BRANDS ---
export const SEED_CLIENTS: Client[] = [
  { id: 1, name: 'Delfi Chocolate', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 2, name: 'Snickers Indonesia', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 3, name: 'Fonterra Brands', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 4, name: 'Moist Diane', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 5, name: 'KOSE Cosmeport', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 6, name: 'MuTouch', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 7, name: 'Sosro Group', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 8, name: 'Batiste Dry Shampoo', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 9, name: 'KINO Family', client_type: 'INTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 10, name: 'L-MEN', client_type: 'INTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 11, name: 'Nutrimart', client_type: 'INTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 12, name: 'Sleek Baby', client_type: 'INTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 13, name: 'PCI Cosmetics', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 14, name: 'Mars Petcare', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 15, name: 'WiZ Lighting', client_type: 'EXTERNAL', is_active: true, created_at: '2026-01-01T00:00:00Z' },
];

// --- CONTENT TYPES ---
export const SEED_CONTENT_TYPES: ContentType[] = [
  { id: 1, name: 'Mockup Set', default_difficulty: 'HIGH', created_at: '2026-01-01T00:00:00Z' },
  { id: 2, name: 'Banner Marketplace', default_difficulty: 'MEDIUM', created_at: '2026-01-01T00:00:00Z' },
  { id: 3, name: 'PDP (Product Detail Page)', default_difficulty: 'MEDIUM', created_at: '2026-01-01T00:00:00Z' },
  { id: 4, name: 'Social Media Post', default_difficulty: 'LOW', created_at: '2026-01-01T00:00:00Z' },
  { id: 5, name: 'Overlay Graphics', default_difficulty: 'MEDIUM', created_at: '2026-01-01T00:00:00Z' },
  { id: 6, name: 'Badge / Sticker', default_difficulty: 'LOW', created_at: '2026-01-01T00:00:00Z' },
  { id: 7, name: 'Katalog Produk', default_difficulty: 'HIGH', created_at: '2026-01-01T00:00:00Z' },
  { id: 8, name: 'Email Newsletter', default_difficulty: 'MEDIUM', created_at: '2026-01-01T00:00:00Z' },
  { id: 9, name: 'Video Thumbnail', default_difficulty: 'LOW', created_at: '2026-01-01T00:00:00Z' },
  { id: 10, name: 'Deck Presentasi', default_difficulty: 'HIGH', created_at: '2026-01-01T00:00:00Z' },
];

// --- HOLIDAYS 2026 (Indonesian National Holidays) ---
export const SEED_HOLIDAYS: Holiday[] = [
  { holiday_date: '2026-01-01', description: 'Tahun Baru Masehi' },
  { holiday_date: '2026-01-29', description: 'Tahun Baru Imlek' },
  { holiday_date: '2026-02-17', description: "Isra' Mi'raj Nabi Muhammad SAW" },
  { holiday_date: '2026-03-22', description: 'Hari Raya Nyepi' },
  { holiday_date: '2026-03-29', description: 'Wafat Isa Al-Masih' },
  { holiday_date: '2026-03-30', description: 'Hari Raya Idul Fitri 1447 H (Hari 1)' },
  { holiday_date: '2026-03-31', description: 'Hari Raya Idul Fitri 1447 H (Hari 2)' },
  { holiday_date: '2026-04-01', description: 'Cuti Bersama Idul Fitri' },
  { holiday_date: '2026-04-02', description: 'Cuti Bersama Idul Fitri' },
  { holiday_date: '2026-04-03', description: 'Cuti Bersama Idul Fitri' },
  { holiday_date: '2026-05-01', description: 'Hari Buruh Internasional' },
  { holiday_date: '2026-05-14', description: 'Kenaikan Isa Al-Masih' },
  { holiday_date: '2026-05-26', description: 'Hari Raya Waisak' },
  { holiday_date: '2026-06-01', description: 'Hari Lahir Pancasila' },
  { holiday_date: '2026-06-06', description: 'Hari Raya Idul Adha 1447 H' },
  { holiday_date: '2026-06-27', description: 'Tahun Baru Hijriyah 1448 H' },
  { holiday_date: '2026-08-17', description: 'Hari Kemerdekaan RI' },
  { holiday_date: '2026-09-05', description: 'Maulid Nabi Muhammad SAW' },
  { holiday_date: '2026-12-25', description: 'Hari Raya Natal' },
  { holiday_date: '2026-12-31', description: 'Cuti Bersama Akhir Tahun' },
];

// --- CREATIVE TASKS ---
const taskIds = Array.from({ length: 55 }, () => generateUUID());

export const SEED_TASKS: CreativeTask[] = [
  // ===== BATCH 1: Closed/Completed tasks (historical - EXCELLENCE) =====
  { id: taskIds[0], task_code: 'REQ-2026-0001', client_id: 1, campaign_name: 'Ramadhan Big Sale 2026', content_type_id: 1, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-03-02', due_date: '2026-03-05', submission_date: '2026-03-04', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'HIGH', design_revision_count: 1, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Delfi_Ramadhan_MockupSet_V2', final_asset_link: 'https://drive.google.com/drive/folders/delfi-ramadhan', notes: 'Urgent campaign', created_by: USER_IDS.sarah, created_at: '2026-03-02T08:00:00Z', updated_at: '2026-03-10T14:00:00Z' },
  { id: taskIds[1], task_code: 'REQ-2026-0002', client_id: 2, campaign_name: 'Snickers Mingyu BAU', content_type_id: 5, task_source: 'ORCA', req_qty: 1, output_qty: 1, req_date: '2026-03-03', due_date: '2026-03-06', submission_date: '2026-03-05', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Snickers_BAU_Overlay_V1', final_asset_link: 'https://drive.google.com/drive/folders/snickers-bau', notes: '', created_by: USER_IDS.reza, created_at: '2026-03-03T09:00:00Z', updated_at: '2026-03-08T16:00:00Z' },
  { id: taskIds[2], task_code: 'REQ-2026-0003', client_id: 3, campaign_name: 'Fonterra Clean Professional 5.5', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 3, output_qty: 3, req_date: '2026-04-07', due_date: '2026-04-10', submission_date: '2026-04-09', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 1, design_pic_id: USER_IDS.nadya, design_difficulty: 'HIGH', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Fonterra_55_MockupSet_V1', final_asset_link: 'https://drive.google.com/drive/folders/fonterra-55', notes: 'Double Date campaign', created_by: USER_IDS.sarah, created_at: '2026-04-07T08:00:00Z', updated_at: '2026-04-14T16:00:00Z' },
  // Historical - GOOD
  { id: taskIds[3], task_code: 'REQ-2026-0004', client_id: 4, campaign_name: 'Moist Diane Summer Hair', content_type_id: 2, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-04-14', due_date: '2026-04-17', submission_date: '2026-04-20', sla_working_days: 4, operational_excellence: 'GOOD', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'MEDIUM', design_revision_count: 2, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'MoistDiane_Summer_Banner_V3', final_asset_link: 'https://drive.google.com/drive/folders/md-summer', notes: 'Client requested 2 revisions', created_by: USER_IDS.reza, created_at: '2026-04-14T08:00:00Z', updated_at: '2026-04-24T14:00:00Z' },
  // Historical - BAD
  { id: taskIds[4], task_code: 'REQ-2026-0005', client_id: 5, campaign_name: 'KOSE Mega Sale 6.6', content_type_id: 7, task_source: 'ECOMMERCE', req_qty: 1, output_qty: 1, req_date: '2026-05-04', due_date: '2026-05-07', submission_date: '2026-05-12', sla_working_days: 6, operational_excellence: 'BAD', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 2, design_pic_id: USER_IDS.bad, design_difficulty: 'HIGH', design_revision_count: 3, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'KOSE_66_Katalog_V4', final_asset_link: 'https://drive.google.com/drive/folders/kose-66', notes: 'Multiple revisions caused SLA breach', created_by: USER_IDS.sarah, created_at: '2026-05-04T08:00:00Z', updated_at: '2026-05-15T16:00:00Z' },
  // More historical
  { id: taskIds[5], task_code: 'REQ-2026-0006', client_id: 6, campaign_name: 'MuTouch BAU Juli', content_type_id: 4, task_source: 'ORCA', req_qty: 4, output_qty: 4, req_date: '2026-06-15', due_date: '2026-06-18', submission_date: '2026-06-17', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'MuTouch_BAU_SocMed_V1', final_asset_link: 'https://drive.google.com/drive/folders/mut-bau', notes: '', created_by: USER_IDS.reza, created_at: '2026-06-15T08:00:00Z', updated_at: '2026-06-20T16:00:00Z' },
  { id: taskIds[6], task_code: 'REQ-2026-0007', client_id: 7, campaign_name: 'Sosro Promo Lebaran', content_type_id: 2, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-03-10', due_date: '2026-03-13', submission_date: '2026-03-12', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Sosro_Lebaran_Banner_V1', final_asset_link: 'https://drive.google.com/drive/folders/sosro-lebaran', notes: '', created_by: USER_IDS.sarah, created_at: '2026-03-10T08:00:00Z', updated_at: '2026-03-16T16:00:00Z' },
  { id: taskIds[7], task_code: 'REQ-2026-0008', client_id: 8, campaign_name: 'Batiste Summer Glow', content_type_id: 3, task_source: 'ECOMMERCE', req_qty: 3, output_qty: 3, req_date: '2026-06-02', due_date: '2026-06-05', submission_date: '2026-06-04', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'MEDIUM', design_revision_count: 1, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Batiste_Summer_PDP_V2', final_asset_link: 'https://drive.google.com/drive/folders/bat-summer', notes: '', created_by: USER_IDS.reza, created_at: '2026-06-02T08:00:00Z', updated_at: '2026-06-09T16:00:00Z' },
  { id: taskIds[8], task_code: 'REQ-2026-0009', client_id: 9, campaign_name: 'KINO Family 7.7', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-06-20', due_date: '2026-06-25', submission_date: '2026-06-24', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'HIGH', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'KINO_77_Mockup_V1', final_asset_link: 'https://drive.google.com/drive/folders/kino-77', notes: '', created_by: USER_IDS.sarah, created_at: '2026-06-20T08:00:00Z', updated_at: '2026-07-01T16:00:00Z' },
  { id: taskIds[9], task_code: 'REQ-2026-0010', client_id: 10, campaign_name: 'L-MEN BAU Agustus', content_type_id: 4, task_source: 'ORCA', req_qty: 5, output_qty: 5, req_date: '2026-07-20', due_date: '2026-07-23', submission_date: '2026-07-22', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'LMEN_BAU_SocMed_V1', final_asset_link: 'https://drive.google.com/drive/folders/lmen-bau', notes: '', created_by: USER_IDS.reza, created_at: '2026-07-20T08:00:00Z', updated_at: '2026-07-25T16:00:00Z' },
  { id: taskIds[10], task_code: 'REQ-2026-0011', client_id: 11, campaign_name: 'Nutrimart 8.8', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-07-28', due_date: '2026-07-31', submission_date: '2026-08-01', sla_working_days: 4, operational_excellence: 'GOOD', requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 1, design_pic_id: USER_IDS.bad, design_difficulty: 'HIGH', design_revision_count: 1, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Nutrimart_88_Mockup_V2', final_asset_link: 'https://drive.google.com/drive/folders/nutri-88', notes: '', created_by: USER_IDS.sarah, created_at: '2026-07-28T08:00:00Z', updated_at: '2026-08-05T16:00:00Z' },
  { id: taskIds[11], task_code: 'REQ-2026-0012', client_id: 12, campaign_name: 'Sleek Baby New Launch', content_type_id: 10, task_source: 'ORCA', req_qty: 1, output_qty: 1, req_date: '2026-08-04', due_date: '2026-08-07', submission_date: '2026-08-11', sla_working_days: 5, operational_excellence: 'BAD', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 2, design_pic_id: USER_IDS.nadya, design_difficulty: 'HIGH', design_revision_count: 2, status_design: 'DESIGN_APPROVED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Sleek_NewLaunch_Deck_V3', final_asset_link: 'https://drive.google.com/drive/folders/sleek-launch', notes: 'Complex deck with multiple revisions', created_by: USER_IDS.reza, created_at: '2026-08-04T08:00:00Z', updated_at: '2026-08-14T16:00:00Z' },

  // ===== BATCH 2: Recent & Active tasks (September 2026) =====
  // Approved - waiting for motion
  { id: taskIds[12], task_code: 'REQ-2026-0013', client_id: 1, campaign_name: 'Delfi 9.9 Mega Sale', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 3, output_qty: 3, req_date: '2026-09-01', due_date: '2026-09-04', submission_date: '2026-09-03', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'HIGH', design_revision_count: 0, status_design: 'DESIGN_APPROVED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Delfi_99_MockupSet_V1', final_asset_link: 'https://drive.google.com/drive/folders/delfi-99', notes: '9.9 campaign', created_by: USER_IDS.sarah, created_at: '2026-09-01T08:00:00Z', updated_at: '2026-09-05T14:00:00Z' },
  // Submitted - awaiting approval
  { id: taskIds[13], task_code: 'REQ-2026-0014', client_id: 2, campaign_name: 'Snickers BAU September', content_type_id: 5, task_source: 'ORCA', req_qty: 1, output_qty: 1, req_date: '2026-09-08', due_date: '2026-09-11', submission_date: '2026-09-10', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'DESIGN_SUBMITTED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Snickers_Sept_Overlay_V1', final_asset_link: 'https://drive.google.com/drive/folders/snickers-sept', notes: '', created_by: USER_IDS.reza, created_at: '2026-09-08T08:00:00Z', updated_at: '2026-09-10T16:00:00Z' },
  // In revision
  { id: taskIds[14], task_code: 'REQ-2026-0015', client_id: 13, campaign_name: 'PCI Cosmetics 10.10 Prep', content_type_id: 2, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-09-10', due_date: '2026-09-15', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'MEDIUM', design_revision_count: 1, status_design: 'DESIGN_REVISION', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: 'Brand requested color change', created_by: USER_IDS.sarah, created_at: '2026-09-10T08:00:00Z', updated_at: '2026-09-18T10:00:00Z' },
  // In Progress tasks
  { id: taskIds[15], task_code: 'REQ-2026-0016', client_id: 14, campaign_name: 'Mars Petcare BAU', content_type_id: 4, task_source: 'ORCA', req_qty: 3, output_qty: 3, req_date: '2026-09-15', due_date: '2026-09-18', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'DESIGN_IN_PROGRESS', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.reza, created_at: '2026-09-15T08:00:00Z', updated_at: '2026-09-16T09:00:00Z' },
  { id: taskIds[16], task_code: 'REQ-2026-0017', client_id: 3, campaign_name: 'Fonterra 10.10', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-09-16', due_date: '2026-09-19', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'HIGH', design_revision_count: 0, status_design: 'DESIGN_IN_PROGRESS', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.sarah, created_at: '2026-09-16T08:00:00Z', updated_at: '2026-09-17T09:00:00Z' },
  { id: taskIds[17], task_code: 'REQ-2026-0018', client_id: 4, campaign_name: 'Moist Diane Autumn Series', content_type_id: 3, task_source: 'ORCA', req_qty: 4, output_qty: 4, req_date: '2026-09-17', due_date: '2026-09-22', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'DESIGN_IN_PROGRESS', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.reza, created_at: '2026-09-17T08:00:00Z', updated_at: '2026-09-18T09:00:00Z' },
  // Assigned tasks
  { id: taskIds[18], task_code: 'REQ-2026-0019', client_id: 5, campaign_name: 'KOSE Autumn Beauty', content_type_id: 8, task_source: 'ORCA', req_qty: 1, output_qty: 1, req_date: '2026-09-18', due_date: '2026-09-23', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'DESIGN_ASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.sarah, created_at: '2026-09-18T08:00:00Z', updated_at: '2026-09-19T09:00:00Z' },
  { id: taskIds[19], task_code: 'REQ-2026-0020', client_id: 15, campaign_name: 'WiZ Smart Lighting Campaign', content_type_id: 9, task_source: 'ECOMMERCE', req_qty: 6, output_qty: 6, req_date: '2026-09-19', due_date: '2026-09-24', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'DESIGN_ASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.reza, created_at: '2026-09-19T08:00:00Z', updated_at: '2026-09-20T09:00:00Z' },
  // Unassigned tasks
  { id: taskIds[20], task_code: 'REQ-2026-0021', client_id: 9, campaign_name: 'KINO Family 10.10 DD', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-09-20', due_date: '2026-09-25', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'DESIGN_UNASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: 'Double Date 10.10', created_by: USER_IDS.sarah, created_at: '2026-09-20T08:00:00Z', updated_at: '2026-09-20T08:00:00Z' },
  { id: taskIds[21], task_code: 'REQ-2026-0022', client_id: 10, campaign_name: 'L-MEN Gym Pack Promo', content_type_id: 6, task_source: 'ORCA', req_qty: 8, output_qty: 8, req_date: '2026-09-21', due_date: '2026-09-26', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'DESIGN_UNASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.reza, created_at: '2026-09-21T08:00:00Z', updated_at: '2026-09-21T08:00:00Z' },
  { id: taskIds[22], task_code: 'REQ-2026-0023', client_id: 6, campaign_name: 'MuTouch x BTS Collab', content_type_id: 2, task_source: 'ECOMMERCE', req_qty: 3, output_qty: 3, req_date: '2026-09-22', due_date: '2026-09-25', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: true, strat_pic_id: null, status_strat: 'PENDING', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'STRAT_PENDING', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: 'Need strategic concept for new collab', created_by: USER_IDS.sarah, created_at: '2026-09-22T08:00:00Z', updated_at: '2026-09-22T08:00:00Z' },
  { id: taskIds[23], task_code: 'REQ-2026-0024', client_id: 12, campaign_name: 'Sleek Baby Holiday Edition', content_type_id: 3, task_source: 'ORCA', req_qty: 5, output_qty: 5, req_date: '2026-09-22', due_date: '2026-09-25', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'DESIGN_UNASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.reza, created_at: '2026-09-22T08:00:00Z', updated_at: '2026-09-22T08:00:00Z' },
  // Draft/New tasks
  { id: taskIds[24], task_code: 'REQ-2026-0025', client_id: 7, campaign_name: 'Sosro Oktober Ceria', content_type_id: 5, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-09-23', due_date: '2026-09-26', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'DESIGN_UNASSIGNED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: '', created_by: USER_IDS.sarah, created_at: '2026-09-23T08:00:00Z', updated_at: '2026-09-23T08:00:00Z' },
  { id: taskIds[25], task_code: 'REQ-2026-0026', client_id: 14, campaign_name: 'Mars Petcare 10.10', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-09-23', due_date: '2026-09-26', submission_date: null, sla_working_days: null, operational_excellence: null, requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'IN_PROGRESS', strat_revision_count: 0, design_pic_id: null, design_difficulty: null, design_revision_count: 0, status_design: 'STRAT_PENDING', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: null, final_asset_link: null, notes: 'Needs custom concept for pet-themed 10.10', created_by: USER_IDS.reza, created_at: '2026-09-23T08:00:00Z', updated_at: '2026-09-23T10:00:00Z' },
  // More historical data for reports
  { id: taskIds[26], task_code: 'REQ-2026-0027', client_id: 1, campaign_name: 'Delfi Valentine Special', content_type_id: 2, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-02-02', due_date: '2026-02-05', submission_date: '2026-02-04', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Delfi_Valentine_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.sarah, created_at: '2026-02-02T08:00:00Z', updated_at: '2026-02-10T16:00:00Z' },
  { id: taskIds[27], task_code: 'REQ-2026-0028', client_id: 2, campaign_name: 'Snickers 3.3 Promo', content_type_id: 5, task_source: 'ECOMMERCE', req_qty: 1, output_qty: 1, req_date: '2026-02-20', due_date: '2026-02-25', submission_date: '2026-02-24', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'Snickers_33_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.reza, created_at: '2026-02-20T08:00:00Z', updated_at: '2026-03-01T16:00:00Z' },
  { id: taskIds[28], task_code: 'REQ-2026-0029', client_id: 3, campaign_name: 'Fonterra BAU Feb', content_type_id: 4, task_source: 'ORCA', req_qty: 3, output_qty: 3, req_date: '2026-02-10', due_date: '2026-02-13', submission_date: '2026-02-16', sla_working_days: 4, operational_excellence: 'GOOD', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'LOW', design_revision_count: 1, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Fonterra_BAU_Feb_V2', final_asset_link: '#', notes: '', created_by: USER_IDS.sarah, created_at: '2026-02-10T08:00:00Z', updated_at: '2026-02-20T16:00:00Z' },
  { id: taskIds[29], task_code: 'REQ-2026-0030', client_id: 9, campaign_name: 'KINO Imlek Promo', content_type_id: 1, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-01-19', due_date: '2026-01-22', submission_date: '2026-01-21', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: true, strat_pic_id: USER_IDS.mahes, status_strat: 'APPROVED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'HIGH', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'KINO_Imlek_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.reza, created_at: '2026-01-19T08:00:00Z', updated_at: '2026-01-27T16:00:00Z' },
  // More for volume
  { id: taskIds[30], task_code: 'REQ-2026-0031', client_id: 10, campaign_name: 'L-MEN Protein Bar Launch', content_type_id: 10, task_source: 'ORCA', req_qty: 1, output_qty: 1, req_date: '2026-05-18', due_date: '2026-05-21', submission_date: '2026-05-25', sla_working_days: 5, operational_excellence: 'BAD', requires_strategic_concept: true, strat_pic_id: USER_IDS.ira, status_strat: 'APPROVED', strat_revision_count: 1, design_pic_id: USER_IDS.yusuf, design_difficulty: 'HIGH', design_revision_count: 2, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'LMEN_ProteinBar_Deck_V3', final_asset_link: '#', notes: '', created_by: USER_IDS.sarah, created_at: '2026-05-18T08:00:00Z', updated_at: '2026-05-28T16:00:00Z' },
  { id: taskIds[31], task_code: 'REQ-2026-0032', client_id: 4, campaign_name: 'Moist Diane 4.4', content_type_id: 2, task_source: 'ECOMMERCE', req_qty: 2, output_qty: 2, req_date: '2026-03-23', due_date: '2026-03-26', submission_date: '2026-03-25', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'MEDIUM', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'READY_TO_ANIMATE', operator_id: null, platform: 'SHOPEE', final_asset_name: 'MoistDiane_44_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.reza, created_at: '2026-03-23T08:00:00Z', updated_at: '2026-03-28T16:00:00Z' },
  { id: taskIds[32], task_code: 'REQ-2026-0033', client_id: 8, campaign_name: 'Batiste BAU April', content_type_id: 6, task_source: 'ORCA', req_qty: 4, output_qty: 4, req_date: '2026-04-06', due_date: '2026-04-09', submission_date: '2026-04-08', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.nadya, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Batiste_BAU_Badge_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.sarah, created_at: '2026-04-06T08:00:00Z', updated_at: '2026-04-12T16:00:00Z' },
  // More September active
  { id: taskIds[33], task_code: 'REQ-2026-0034', client_id: 11, campaign_name: 'Nutrimart Healthy Living', content_type_id: 4, task_source: 'ORCA', req_qty: 3, output_qty: 3, req_date: '2026-09-15', due_date: '2026-09-18', submission_date: '2026-09-17', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.bad, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'DESIGN_SUBMITTED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'Nutrimart_Healthy_SocMed_V1', final_asset_link: 'https://drive.google.com/drive/folders/nutri-healthy', notes: '', created_by: USER_IDS.sarah, created_at: '2026-09-15T08:00:00Z', updated_at: '2026-09-17T14:00:00Z' },
  { id: taskIds[34], task_code: 'REQ-2026-0035', client_id: 15, campaign_name: 'WiZ BAU September', content_type_id: 4, task_source: 'ORCA', req_qty: 2, output_qty: 2, req_date: '2026-09-08', due_date: '2026-09-11', submission_date: '2026-09-10', sla_working_days: 2, operational_excellence: 'EXCELLENCE', requires_strategic_concept: false, strat_pic_id: null, status_strat: 'NOT_REQUIRED', strat_revision_count: 0, design_pic_id: USER_IDS.yusuf, design_difficulty: 'LOW', design_revision_count: 0, status_design: 'TASK_CLOSED', motion_readiness: 'WAITING_ASSET_GD', operator_id: null, platform: 'TIKTOK', final_asset_name: 'WiZ_BAU_Sept_V1', final_asset_link: '#', notes: '', created_by: USER_IDS.reza, created_at: '2026-09-08T08:00:00Z', updated_at: '2026-09-12T16:00:00Z' },
];

// --- MOTION TASKS ---
export const SEED_MOTION_TASKS: MotionTask[] = [
  // Completed motion tasks
  { id: generateUUID(), task_id: taskIds[0], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_2_MEDIUM', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-03-08', link_motion: 'https://drive.google.com/folders/delfi-ramadhan-motion', notes: '', created_at: '2026-03-05T10:00:00Z', updated_at: '2026-03-08T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[1], motion_pic_id: USER_IDS.bima, motion_difficulty: 'LVL_1_SIMPLE', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-03-07', link_motion: 'https://drive.google.com/folders/snickers-bau-motion', notes: '', created_at: '2026-03-06T10:00:00Z', updated_at: '2026-03-07T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[2], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_3_ADVANCED', motion_revision_count: 1, status_motion: 'COMPLETED', apply_date: '2026-04-12', link_motion: 'https://drive.google.com/folders/fonterra-55-motion', notes: 'AI background required', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-12T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[3], motion_pic_id: USER_IDS.bima, motion_difficulty: 'LVL_2_MEDIUM', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-04-22', link_motion: 'https://drive.google.com/folders/md-summer-motion', notes: '', created_at: '2026-04-21T10:00:00Z', updated_at: '2026-04-22T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[6], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_1_SIMPLE', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-03-14', link_motion: 'https://drive.google.com/folders/sosro-lebaran-motion', notes: '', created_at: '2026-03-13T10:00:00Z', updated_at: '2026-03-14T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[8], motion_pic_id: USER_IDS.bima, motion_difficulty: 'LVL_4_PERIOD', motion_revision_count: 1, status_motion: 'COMPLETED', apply_date: '2026-06-28', link_motion: 'https://drive.google.com/folders/kino-77-motion', notes: 'Multi-period dates', created_at: '2026-06-25T10:00:00Z', updated_at: '2026-06-28T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[10], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_3_ADVANCED', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-08-04', link_motion: 'https://drive.google.com/folders/nutri-88-motion', notes: '', created_at: '2026-08-02T10:00:00Z', updated_at: '2026-08-04T16:00:00Z' },
  // Active motion task (from recent approved design)
  { id: generateUUID(), task_id: taskIds[12], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_3_ADVANCED', motion_revision_count: 0, status_motion: 'IN_PROGRESS', apply_date: '2026-09-08', link_motion: null, notes: '9.9 campaign - high priority', created_at: '2026-09-05T10:00:00Z', updated_at: '2026-09-06T09:00:00Z' },
  // Queued motion tasks
  { id: generateUUID(), task_id: taskIds[26], motion_pic_id: USER_IDS.bima, motion_difficulty: 'LVL_2_MEDIUM', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-02-08', link_motion: '#', notes: '', created_at: '2026-02-06T10:00:00Z', updated_at: '2026-02-08T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[27], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_1_SIMPLE', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-02-26', link_motion: '#', notes: '', created_at: '2026-02-25T10:00:00Z', updated_at: '2026-02-26T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[29], motion_pic_id: USER_IDS.bima, motion_difficulty: 'LVL_4_PERIOD', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-01-25', link_motion: '#', notes: '', created_at: '2026-01-23T10:00:00Z', updated_at: '2026-01-25T16:00:00Z' },
  { id: generateUUID(), task_id: taskIds[31], motion_pic_id: USER_IDS.jova, motion_difficulty: 'LVL_2_MEDIUM', motion_revision_count: 0, status_motion: 'COMPLETED', apply_date: '2026-03-27', link_motion: '#', notes: '', created_at: '2026-03-26T10:00:00Z', updated_at: '2026-03-27T16:00:00Z' },
];

// --- TASK REVISIONS ---
export const SEED_REVISIONS: TaskRevision[] = [
  { id: generateUUID(), task_id: taskIds[0], stage: 'DESIGN', revision_number: 1, reason_category: 'CLIENT_CHANGE', notes: 'Client requested different color scheme for Ramadhan theme', requested_by: USER_IDS.sarah, created_at: '2026-03-04T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[2], stage: 'STRATEGIC', revision_number: 1, reason_category: 'BRIEF_MISMATCH', notes: 'Strategic concept didn\'t align with 5.5 campaign brief', requested_by: USER_IDS.alfie, created_at: '2026-04-08T14:00:00Z' },
  { id: generateUUID(), task_id: taskIds[3], stage: 'DESIGN', revision_number: 1, reason_category: 'CLIENT_CHANGE', notes: 'Brand requested product packshot repositioning', requested_by: USER_IDS.reza, created_at: '2026-04-17T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[3], stage: 'DESIGN', revision_number: 2, reason_category: 'TYPO', notes: 'Typographical error in discount percentage', requested_by: USER_IDS.reza, created_at: '2026-04-18T14:00:00Z' },
  { id: generateUUID(), task_id: taskIds[4], stage: 'STRATEGIC', revision_number: 1, reason_category: 'SCOPE_CHANGE', notes: 'Additional product variants need to be included', requested_by: USER_IDS.sarah, created_at: '2026-05-06T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[4], stage: 'STRATEGIC', revision_number: 2, reason_category: 'CLIENT_CHANGE', notes: 'Client changed campaign direction entirely', requested_by: USER_IDS.sarah, created_at: '2026-05-07T14:00:00Z' },
  { id: taskIds[4] + '-rev3', task_id: taskIds[4], stage: 'DESIGN', revision_number: 1, reason_category: 'QUALITY_ISSUE', notes: 'Resolution too low for print katalog', requested_by: USER_IDS.alfie, created_at: '2026-05-09T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[4], stage: 'DESIGN', revision_number: 2, reason_category: 'BRIEF_MISMATCH', notes: 'Color palette doesn\'t match brand guideline update', requested_by: USER_IDS.sarah, created_at: '2026-05-10T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[4], stage: 'DESIGN', revision_number: 3, reason_category: 'TYPO', notes: 'Product name misspelled', requested_by: USER_IDS.reza, created_at: '2026-05-11T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[14], stage: 'DESIGN', revision_number: 1, reason_category: 'CLIENT_CHANGE', notes: 'PCI wants different color palette for autumn', requested_by: USER_IDS.sarah, created_at: '2026-09-16T14:00:00Z' },
  { id: generateUUID(), task_id: taskIds[7], stage: 'DESIGN', revision_number: 1, reason_category: 'TYPO', notes: 'Price tag error', requested_by: USER_IDS.reza, created_at: '2026-06-03T14:00:00Z' },
  { id: generateUUID(), task_id: taskIds[10], stage: 'STRATEGIC', revision_number: 1, reason_category: 'SCOPE_CHANGE', notes: 'Additional product line to include', requested_by: USER_IDS.sarah, created_at: '2026-07-30T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[10], stage: 'DESIGN', revision_number: 1, reason_category: 'CLIENT_CHANGE', notes: 'Different header layout requested', requested_by: USER_IDS.sarah, created_at: '2026-08-01T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[11], stage: 'STRATEGIC', revision_number: 1, reason_category: 'BRIEF_MISMATCH', notes: 'Deck structure didn\'t follow product launch template', requested_by: USER_IDS.alfie, created_at: '2026-08-06T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[11], stage: 'STRATEGIC', revision_number: 2, reason_category: 'SCOPE_CHANGE', notes: 'Additional market data slides requested', requested_by: USER_IDS.sarah, created_at: '2026-08-07T14:00:00Z' },
  { id: generateUUID(), task_id: taskIds[11], stage: 'DESIGN', revision_number: 1, reason_category: 'QUALITY_ISSUE', notes: 'Charts need higher resolution export', requested_by: USER_IDS.alfie, created_at: '2026-08-09T10:00:00Z' },
  { id: generateUUID(), task_id: taskIds[11], stage: 'DESIGN', revision_number: 2, reason_category: 'TYPO', notes: 'Statistical data correction in slides 4-6', requested_by: USER_IDS.reza, created_at: '2026-08-10T10:00:00Z' },
];

// --- AUDIT LOGS ---
export const SEED_AUDIT_LOGS: AuditLog[] = [
  { id: 1, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0001', action: 'CREATE', performed_by: USER_IDS.sarah, performer_name: 'Sarah Amelia', before_state: null, after_state: { status_design: 'STRAT_PENDING', client: 'Delfi Chocolate' }, timestamp: '2026-03-02T08:00:00Z' },
  { id: 2, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0001', action: 'ASSIGN', performed_by: USER_IDS.alfie, performer_name: 'Alfie Rahman', before_state: { design_pic: null, status_design: 'DESIGN_UNASSIGNED' }, after_state: { design_pic: 'Nadya Aulia', status_design: 'DESIGN_ASSIGNED', difficulty: 'HIGH' }, timestamp: '2026-03-02T09:30:00Z' },
  { id: 3, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0001', action: 'STATUS_TRANSITION', performed_by: USER_IDS.nadya, performer_name: 'Nadya Aulia', before_state: { status_design: 'DESIGN_ASSIGNED' }, after_state: { status_design: 'DESIGN_IN_PROGRESS' }, timestamp: '2026-03-02T10:00:00Z' },
  { id: 4, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0001', action: 'SUBMIT', performed_by: USER_IDS.nadya, performer_name: 'Nadya Aulia', before_state: { status_design: 'DESIGN_IN_PROGRESS', submission_date: null }, after_state: { status_design: 'DESIGN_SUBMITTED', submission_date: '2026-03-04', sla_working_days: 2, operational_excellence: 'EXCELLENCE' }, timestamp: '2026-03-04T14:22:10Z' },
  { id: 5, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0001', action: 'APPROVE', performed_by: USER_IDS.alfie, performer_name: 'Alfie Rahman', before_state: { status_design: 'DESIGN_SUBMITTED' }, after_state: { status_design: 'DESIGN_APPROVED' }, timestamp: '2026-03-05T09:00:00Z' },
  { id: 6, entity_name: 'motion_tasks', entity_id: 'REQ-2026-0001', action: 'CREATE', performed_by: USER_IDS.alfie, performer_name: 'System (Auto)', before_state: null, after_state: { status_motion: 'QUEUED', motion_pic: 'Jova Dirgantara' }, timestamp: '2026-03-05T09:01:00Z' },
  { id: 7, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0013', action: 'CREATE', performed_by: USER_IDS.sarah, performer_name: 'Sarah Amelia', before_state: null, after_state: { status_design: 'STRAT_PENDING', client: 'Delfi Chocolate', campaign: 'Delfi 9.9 Mega Sale' }, timestamp: '2026-09-01T08:00:00Z' },
  { id: 8, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0013', action: 'ASSIGN', performed_by: USER_IDS.alfie, performer_name: 'Alfie Rahman', before_state: { design_pic: null }, after_state: { design_pic: 'Yusuf Pratama', difficulty: 'HIGH' }, timestamp: '2026-09-01T09:00:00Z' },
  { id: 9, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0015', action: 'REVISION_REQUEST', performed_by: USER_IDS.sarah, performer_name: 'Sarah Amelia', before_state: { status_design: 'DESIGN_SUBMITTED', revision_count: 0 }, after_state: { status_design: 'DESIGN_REVISION', revision_count: 1 }, timestamp: '2026-09-16T14:00:00Z' },
  { id: 10, entity_name: 'creative_tasks', entity_id: 'REQ-2026-0016', action: 'STATUS_TRANSITION', performed_by: USER_IDS.nadya, performer_name: 'Nadya Aulia', before_state: { status_design: 'DESIGN_ASSIGNED' }, after_state: { status_design: 'DESIGN_IN_PROGRESS' }, timestamp: '2026-09-16T09:00:00Z' },
];

// --- NOTIFICATIONS ---
export const SEED_NOTIFICATIONS: Notification[] = [
  { id: generateUUID(), user_id: USER_IDS.nadya, title: 'Task Assigned', message: 'Anda ditugaskan mengerjakan REQ-2026-0019 - KOSE Autumn Beauty (Medium). Due: 23 Sep.', type: 'info', read: false, link: '/dashboard/tasks', created_at: '2026-09-19T09:00:00Z' },
  { id: generateUUID(), user_id: USER_IDS.yusuf, title: 'Task Assigned', message: 'Anda ditugaskan mengerjakan REQ-2026-0020 - WiZ Smart Lighting (Low). Due: 24 Sep.', type: 'info', read: false, link: '/dashboard/tasks', created_at: '2026-09-20T09:00:00Z' },
  { id: generateUUID(), user_id: USER_IDS.alfie, title: 'SLA Warning', message: '[WARNING] REQ-2026-0016 Mars Petcare BAU jatuh tempo besok (18 Sep) - status masih In Progress.', type: 'warning', read: false, link: '/dashboard/tasks', created_at: '2026-09-17T09:00:00Z' },
  { id: generateUUID(), user_id: USER_IDS.jova, title: 'Motion Handoff', message: '[HANDOFF] Desain Delfi 9.9 Mega Sale telah disetujui. Subtask motion telah dibuat.', type: 'success', read: true, link: '/dashboard/motion', created_at: '2026-09-05T10:00:00Z' },
  { id: generateUUID(), user_id: USER_IDS.alfie, title: 'New Unassigned Tasks', message: '4 tiket baru menunggu penugasan PIC: REQ-2026-0021, 0022, 0024, 0025', type: 'warning', read: false, link: '/dashboard/tasks', created_at: '2026-09-23T08:30:00Z' },
  { id: generateUUID(), user_id: USER_IDS.bad, title: 'Revision Requested', message: 'REQ-2026-0015 PCI Cosmetics memerlukan revisi - Client Change: Color palette update', type: 'warning', read: true, link: '/dashboard/tasks', created_at: '2026-09-16T14:30:00Z' },
];
